---
- name: Install fzf
  package:
    name: fzf
    state: present
  when: ansible_distribution | lower == "ubuntu"

- name: CentOS fzf install
  include_tasks: centos_install.yml
  when: ansible_distribution | lower == "centos"
